x-dev: &dev
  environment:
    DEBUG: "1"
  volumes:
    - ./web:/usr/src/app

services:
  web:
    <<: *dev
    ports:
      - "127.0.0.1:8000:8000"
  worker-scan: *dev
  worker-io: *dev
  worker-orch: *dev
  beat: *dev
  migrate: *dev
  db:
    ports:
      - "127.0.0.1:5432:5432"
