# Generated by Django 3.2.23 on 2026-10-07 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_chaosapikey_hackeroneapikey_inappnotification_userpreferences'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('startScan', '0003_phase0_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('root_domain', 'root_domain'), ('hostname', 'hostname'), ('ip', 'ip'), ('cidr', 'cidr')], max_length=20)),
                ('value', models.CharField(max_length=1000)),
                ('scope_tier', models.CharField(choices=[('owned_root', 'owned_root'), ('owned_host', 'owned_host'), ('co_brand', 'co_brand'), ('candidate', 'candidate'), ('rejected', 'rejected')], default='candidate', max_length=20)),
                ('active_authorized', models.BooleanField(default=False)),
                ('state', models.CharField(choices=[('active', 'active'), ('missing', 'missing'), ('stale', 'stale'), ('retired', 'retired')], default='active', max_length=20)),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('missed_count', models.IntegerField(default=0)),
                ('sources', models.JSONField(blank=True, default=list)),
                ('decision_reason', models.TextField(blank=True, default='')),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('page_title', models.CharField(blank=True, max_length=1000, null=True)),
                ('webserver', models.CharField(blank=True, max_length=1000, null=True)),
                ('content_type', models.CharField(blank=True, max_length=100, null=True)),
                ('content_length', models.IntegerField(blank=True, null=True)),
                ('response_time', models.FloatField(blank=True, null=True)),
                ('cname', models.CharField(blank=True, max_length=5000, null=True)),
                ('is_cdn', models.BooleanField(default=False)),
                ('cdn_name', models.CharField(blank=True, max_length=200, null=True)),
                ('screenshot_path', models.CharField(blank=True, max_length=1000, null=True)),
                ('cadence_tier', models.CharField(default='standard', max_length=20)),
                ('request_headers', models.JSONField(blank=True, null=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ip_addresses', models.ManyToManyField(blank=True, related_name='assets', to='startScan.IpAddress')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='startScan.asset')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.project')),
                ('tags', models.ManyToManyField(blank=True, related_name='assets', to='startScan.Tag')),
                ('technologies', models.ManyToManyField(blank=True, related_name='assets', to='startScan.Technology')),
            ],
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['project', 'kind'], name='asset_proj_kind_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['project', 'scope_tier'], name='asset_proj_scope_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['project', 'state'], name='asset_proj_state_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together={('project', 'kind', 'value')},
        ),
    ]
