# Generated by Django 3.2.23 on 2026-10-07 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0002_chaosapikey_hackeroneapikey_inappnotification_userpreferences'),
        ('startScan', '0004_auto_20261007_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(default='normal', max_length=20)),
                ('status', models.IntegerField(choices=[(-1, -1), (0, 0), (1, 1), (2, 2), (3, 3)], default=-1)),
                ('results_dir', models.CharField(blank=True, default='', max_length=200)),
                ('start_scan_date', models.DateTimeField()),
                ('stop_scan_date', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.CharField(blank=True, max_length=300, null=True)),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.project')),
                ('root_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_runs', to='startScan.asset')),
            ],
        ),
        migrations.CreateModel(
            name='ScanJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('discovery', 'discovery'), ('resolve', 'resolve'), ('ports', 'ports'), ('probe', 'probe'), ('crawl', 'crawl'), ('dast', 'dast'), ('code', 'code')], max_length=20)),
                ('status', models.IntegerField(choices=[(-1, -1), (0, 0), (1, 1), (2, 2), (3, 3)], default=-1)),
                ('started', models.DateTimeField(blank=True, null=True)),
                ('finished', models.DateTimeField(blank=True, null=True)),
                ('celery_id', models.CharField(blank=True, max_length=100, null=True)),
                ('output_path', models.CharField(blank=True, max_length=300, null=True)),
                ('error_message', models.CharField(blank=True, max_length=300, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_jobs', to='startScan.asset')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='startScan.scanrun')),
            ],
        ),
        migrations.AddIndex(
            model_name='scanjob',
            index=models.Index(fields=['run', 'stage'], name='scanjob_run_stage_idx'),
        ),
        migrations.AddIndex(
            model_name='scanjob',
            index=models.Index(fields=['asset', 'stage'], name='scanjob_asset_stage_idx'),
        ),
    ]
