# Generated by Django 3.2.23 on 2026-10-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0007_migrate_to_assets'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanrun',
            name='mode',
            field=models.CharField(choices=[('asm', 'asm'), ('scanner', 'scanner'), ('full', 'full')], default='full', max_length=10),
        ),
    ]
