# Generated by Django 3.2.23 on 2026-10-09 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0009_remove_vulnerability_hackerone_report_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directoryscan',
            name='dir_subscan_ids',
        ),
        migrations.RemoveField(
            model_name='directoryscan',
            name='directory_files',
        ),
        migrations.RemoveField(
            model_name='metafinderdocument',
            name='scan_history',
        ),
        migrations.RemoveField(
            model_name='metafinderdocument',
            name='subdomain',
        ),
        migrations.RemoveField(
            model_name='metafinderdocument',
            name='target_domain',
        ),
        migrations.RemoveField(
            model_name='scanhistory',
            name='buckets',
        ),
        migrations.RemoveField(
            model_name='scanhistory',
            name='dorks',
        ),
        migrations.RemoveField(
            model_name='scanhistory',
            name='emails',
        ),
        migrations.RemoveField(
            model_name='scanhistory',
            name='employees',
        ),
        migrations.RemoveField(
            model_name='subdomain',
            name='directories',
        ),
        migrations.RemoveField(
            model_name='subdomain',
            name='waf',
        ),
        migrations.DeleteModel(
            name='DirectoryFile',
        ),
        migrations.DeleteModel(
            name='DirectoryScan',
        ),
        migrations.DeleteModel(
            name='Dork',
        ),
        migrations.DeleteModel(
            name='Email',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='MetaFinderDocument',
        ),
        migrations.DeleteModel(
            name='S3Bucket',
        ),
        migrations.DeleteModel(
            name='Waf',
        ),
    ]
