# Generated by Django 3.2.23 on 2026-10-09 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0010_remove_osint_dirscan_waf_s3_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='scope_tier',
            field=models.CharField(choices=[('owned_root', 'owned_root'), ('owned_host', 'owned_host'), ('co_brand', 'co_brand'), ('candidate', 'candidate'), ('rejected', 'rejected'), ('dependency', 'dependency')], default='candidate', max_length=20),
        ),
    ]
