# Generated by Django 3.2.23 on 2026-10-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0012_demote_auto_owned_ips'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='last_resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
