# Generated by Django 3.2.23 on 2026-10-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0013_asset_last_resolved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='enrichment',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
