# Generated by Django 3.2.23 on 2026-10-09 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_chaosapikey_hackeroneapikey_inappnotification_userpreferences'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HackerOneAPIKey',
        ),
        migrations.DeleteModel(
            name='UserPreferences',
        ),
    ]
