# Generated by Django 3.2.23 on 2026-10-09 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('targetApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='h1_team_handle',
        ),
    ]
