# Generated by Django 3.2.23 on 2026-10-07 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanEngine', '0002_hackerone_send_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='enginetype',
            name='profile',
            field=models.CharField(choices=[('quick', 'Quick'), ('normal', 'Normal'), ('thorough', 'Thorough'), ('passive', 'Passive')], default='normal', max_length=20),
        ),
    ]
