# Generated by Django 3.2.23 on 2026-10-09 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanEngine', '0004_stamp_engine_profiles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InstalledExternalTool',
        ),
    ]
