# Generated by Django 3.2.23 on 2026-10-09 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanEngine', '0005_remove_tool_arsenal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hackerone',
        ),
    ]
