# Generated by Django 3.2.23 on 2026-10-09 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanEngine', '0006_remove_hackerone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vulnerabilityreportsetting',
            old_name='show_rengine_banner',
            new_name='show_limes_banner',
        ),
    ]
